# Generated by Django 2.2.6 on 2019-12-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anciano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('edad', models.IntegerField()),
                ('noHistoriaClinica', models.IntegerField()),
                ('tieneDieta', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Joven',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('edad', models.IntegerField()),
                ('noHistoriaClinica', models.IntegerField()),
                ('fumador', models.BooleanField()),
                ('anos_fumando', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('edad', models.IntegerField()),
                ('noHistoriaClinica', models.IntegerField()),
                ('peso', models.IntegerField()),
                ('estatura', models.IntegerField()),
            ],
        ),
    ]
