# Generated by Django 2.2.6 on 2019-12-07 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_auto_20191207_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anciano',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='anciano',
            name='id',
        ),
        migrations.RemoveField(
            model_name='anciano',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='joven',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='joven',
            name='id',
        ),
        migrations.RemoveField(
            model_name='joven',
            name='noHistoriaClinica',
        ),
        migrations.RemoveField(
            model_name='joven',
            name='nombre',
        ),
        migrations.AddField(
            model_name='anciano',
            name='person_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personas.Person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joven',
            name='person_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personas.Person'),
            preserve_default=False,
        ),
    ]
