# Generated by Django 2.2.6 on 2019-12-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_auto_20191207_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anciano',
            name='noHistoriaClinica',
        ),
        migrations.RemoveField(
            model_name='nino',
            name='noHistoriaClinica',
        ),
        migrations.AddField(
            model_name='person',
            name='noHistoriaClinica',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
