# Generated by Django 2.2.6 on 2019-12-07 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0006_person_consulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='listaEspera',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
    ]
